# Generated by Django 6.0.6 on 2026-06-09 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEarningsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_sales', models.FloatField(default=0.0)),
                ('weekly_sales', models.FloatField(default=0.0)),
                ('total_sales', models.FloatField(default=0.0)),
                ('ride_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
