# Generated by Django 6.0.2 on 2026-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='insurance_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driververification',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driververification',
            name='roadworthy_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driververification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='driververification',
            name='vehicle_video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
