# Generated by Django 6.0.2 on 2026-04-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_bio_profile_city_profile_emergency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
