# Generated by Django 6.0.2 on 2026-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='assigned_category',
            field=models.CharField(choices=[('none', 'Not Assigned'), ('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya')], default='none', help_text='Category assigned to the driver upon verification', max_length=20),
        ),
    ]
