# Generated by Django 6.0.2 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_driververification_assigned_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acceptance_rate',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cancellation_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(default='Silver', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
    ]
