# Generated by Django 6.0.2 on 2026-04-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_acceptance_rate_profile_cancellation_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driververification',
            old_name='id_card_image_url',
            new_name='id_card_url',
        ),
        migrations.RenameField(
            model_name='driververification',
            old_name='license_image_url',
            new_name='license_url',
        ),
    ]
