# Generated by Django 6.0.2 on 2026-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_id_card_image_url_driververification_id_card_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
