# Generated by Django 6.0.2 on 2026-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='missed_opportunities_count',
            field=models.IntegerField(default=0),
        ),
    ]
