# Generated by Django 6.0.2 on 2026-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_referral_code_profile_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
