# Generated by Django 5.2.13 on 2026-05-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_location_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
