# Generated by Django 6.0.2 on 2026-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_last_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_navigate',
            field=models.BooleanField(default=False),
        ),
    ]
