# Generated by Django 6.0.4 on 2026-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='id_card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driververification',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
