# Generated by Django 6.0.6 on 2026-06-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_driververification_id_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
