# Generated by Django 6.0.6 on 2026-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driververification',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
