# Generated by Django 6.0.6 on 2026-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_driververification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_deliveries',
            field=models.BooleanField(default=False, help_text='Opt-in to receive courier delivery requests'),
        ),
    ]
