# Generated by Django 5.0.14 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_receive_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driververification',
            name='assigned_category',
            field=models.CharField(choices=[('none', 'Not Assigned'), ('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya'), ('motorbike', 'Flexy Motorbike')], default='none', help_text='Category assigned to the driver upon verification', max_length=20),
        ),
    ]
