# Generated by Django 5.0.14 on 2026-07-16 06:59

import core_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_driververification_assigned_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driververification',
            name='assigned_category',
            field=models.CharField(choices=core_settings.models.get_assigned_categories, default='none', help_text='Category assigned to the driver upon verification', max_length=20),
        ),
    ]
