# Generated by Django 5.0.14 on 2026-07-21 21:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_driververification_assigned_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
