# Generated by Django 5.0.14 on 2026-07-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_profile_last_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_biometric_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
