services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:ravendb@host.docker.internal:5432/flexyride_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - redis
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_worker:
    build: .
    command: celery -A flexy_backend worker -l info --pool=solo
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:ravendb@host.docker.internal:5432/flexyride_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - redis
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
