# Generated by Django 6.0.2 on 2026-04-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_user_apple_id_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('partner', 'Partner'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='rider', max_length=50),
        ),
    ]
