# Generated by Django 6.0.6 on 2026-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('partner', 'Partner'), ('support', 'Customer Support'), ('finance', 'Finance'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, default='rider', max_length=50),
        ),
    ]
