# Generated by Django 6.0.6 on 2026-06-27 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
