# Generated by Django 6.0.4 on 2026-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Rider, Driver, Partner', max_length=50)),
                ('quote', models.TextField()),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Alternative to cover_image for external URLs', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Alternative to cover_image for external URLs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
