# Generated by Django 6.0.2 on 2026-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimonial_blogpost_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, help_text='For map pulsars', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, help_text='For map pulsars', null=True),
        ),
    ]
