# Generated by Django 6.0.2 on 2026-04-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('riders', 'For Riders'), ('drivers', 'For Drivers'), ('payments', 'Payments'), ('safety', 'Safety'), ('general', 'General')], default='general', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('operations', 'Operations'), ('marketing', 'Marketing'), ('support', 'Customer Support'), ('finance', 'Finance'), ('design', 'Design')], max_length=20)),
                ('location', models.CharField(default='Accra, Ghana', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('apply_url', models.URLField(blank=True, help_text='External application link (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('company', 'Company News'), ('safety', 'Safety Tips'), ('driver', 'Driver Stories'), ('travel', 'Ghana Travel'), ('product', 'Product Updates')], default='company', max_length=20),
        ),
    ]
