# Generated by Django 6.0.2 on 2026-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_brandfeature_herobanner_legaldocument_safetyfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
