# Generated by Django 6.0.2 on 2026-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_websitesettings_whatsapp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandfeature',
            name='icon_emoji',
        ),
        migrations.RemoveField(
            model_name='safetyfeature',
            name='icon_emoji',
        ),
        migrations.AddField(
            model_name='brandfeature',
            name='icon_name',
            field=models.CharField(default='star', help_text='Lucide icon name (e.g. shield, zap)', max_length=50),
        ),
        migrations.AddField(
            model_name='safetyfeature',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g. shield, alert-triangle)', max_length=50),
        ),
    ]
