# Generated by Django 6.0.2 on 2026-05-09 19:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_brandfeature_icon_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='benefits',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='responsibilities',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Responsibilities'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='requirements',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Requirements'),
        ),
    ]
