# Generated by Django 6.0.2 on 2026-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_jobopening_benefits_jobopening_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
