# Generated by Django 6.0.2 on 2026-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_jobopening_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('about', 'About Us')], max_length=20),
        ),
    ]
