# Generated by Django 6.0.2 on 2026-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_jobopening_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=models.TextField(help_text='Plain text or HTML supported. Use line breaks to separate paragraphs.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Responsibilities'),
        ),
    ]
