# Generated by Django 6.0.2 on 2026-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_jobopening_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='about_company',
            field=models.TextField(blank=True, help_text='Brief overview of the company.', verbose_name='About the Company'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='how_to_apply',
            field=models.TextField(blank=True, help_text='Application instructions (Email, WhatsApp, etc.)', verbose_name='How to Apply'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=models.TextField(help_text='Main job description. Use line breaks for paragraphs.', verbose_name='Description'),
        ),
    ]
