# Generated by Django 5.2.14 on 2026-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_jobopening_about_company_jobopening_how_to_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandfeature',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a custom logo or image', null=True, upload_to='brand_features/'),
        ),
        migrations.AlterField(
            model_name='brandfeature',
            name='icon_name',
            field=models.CharField(blank=True, default='star', help_text='Lucide icon name (e.g. shield, zap)', max_length=50, null=True),
        ),
    ]
