# Generated by Django 6.0.2 on 2026-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_brandfeature_image_alter_brandfeature_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandfeature',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link when this feature is clicked', max_length=500, null=True),
        ),
    ]
