# Generated by Django 6.0.6 on 2026-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_brandfeature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='driver_download_url',
            field=models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.flexyride.driver', help_text='Link for driver app downloads', max_length=500),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='passenger_download_url',
            field=models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.flexyride.app', help_text='Link for passenger app downloads', max_length=500),
        ),
    ]
