# Generated by Django 6.0.6 on 2026-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_websitesettings_driver_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='driver_download_url',
            field=models.URLField(blank=True, help_text="Link for driver app downloads. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='passenger_download_url',
            field=models.URLField(blank=True, help_text="Link for passenger app downloads. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
    ]
