# Generated by Django 6.0.6 on 2026-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_websitesettings_driver_download_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='driver_download_url',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='passenger_download_url',
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='driver_app_store_url',
            field=models.URLField(blank=True, help_text="Driver App iOS App Store link. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='driver_play_store_url',
            field=models.URLField(blank=True, help_text="Driver App Google Play link. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='passenger_app_store_url',
            field=models.URLField(blank=True, help_text="Passenger App iOS App Store link. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='passenger_play_store_url',
            field=models.URLField(blank=True, help_text="Passenger App Google Play link. Leave blank to display 'Launching Soon'", max_length=500, null=True),
        ),
    ]
