# Generated by Django 5.0.14 on 2026-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_websitesettings_driver_download_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Lower number = shown first')),
            ],
            options={
                'verbose_name': 'Driver Benefit',
                'verbose_name_plural': 'Driver Benefits',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('safety', 'Safety'), ('careers', 'Careers'), ('contact', 'Contact'), ('drive_with_us', 'Drive With Us')], max_length=50, unique=True),
        ),
    ]
