# Generated by Django 5.0.14 on 2026-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_driverbenefit_alter_herobanner_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='shield-check', help_text='Lucide icon name (e.g. shield-check, clock, banknote, star)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Passenger Benefit',
                'verbose_name_plural': 'Passenger Benefits',
                'ordering': ['order', 'id'],
            },
        ),
    ]
