# Generated by Django 5.0.14 on 2026-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_passengerbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='category',
            field=models.CharField(choices=[('rides', 'Rides'), ('drivers', 'Drivers'), ('delivery', 'Delivery'), ('general', 'General & Privacy')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('about', 'About Us'), ('driver_terms', 'Driver Terms'), ('delivery_terms', 'Delivery Terms')], max_length=20),
        ),
    ]
