# Generated by Django 5.0.14 on 2026-08-16 12:48

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_legaldocument_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subtitle', models.TextField(blank=True, help_text='Lead paragraph or short summary')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('category', models.CharField(choices=[('initiatives', 'Initiatives'), ('partnerships', 'Partnerships'), ('events', 'Events'), ('impact', 'Impact Stories'), ('reports', 'Reports'), ('announcements', 'Announcements')], default='announcements', max_length=30)),
                ('location', models.CharField(default='Accra, Ghana', max_length=100)),
                ('is_immediate_release', models.BooleanField(default=True, help_text='Displays FOR IMMEDIATE RELEASE badge')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='press/')),
                ('cover_image_url', models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('media_contact_name', models.CharField(default='FlexyRide Media Team', max_length=100)),
                ('media_contact_email', models.EmailField(default='press@flexyridegh.com', max_length=254)),
                ('media_contact_phone', models.CharField(default='+233 30 200 0000', max_length=30)),
                ('about_boilerplate', models.TextField(default="FlexyRide is Ghana's leading ride-hailing and urban logistics platform dedicated to providing safe, reliable, and affordable mobility solutions.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('about', 'About Us'), ('driver_terms', 'Driver Terms'), ('delivery_terms', 'Delivery Terms')], max_length=20),
        ),
        migrations.CreateModel(
            name='PressDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. FlexyRide Impact 2026 Overview (PDF)', max_length=200)),
                ('file_type', models.CharField(default='PDF', help_text='PDF, ZIP, DOCX, etc.', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='press_downloads/')),
                ('external_url', models.URLField(blank=True, help_text='External URL if not uploading file directly', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('press_release', models.ForeignKey(blank=True, help_text='Optionally attach to specific press release', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='website.pressrelease')),
            ],
        ),
    ]
