# Generated by Django 6.0.2 on 2026-04-15 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tier', help_text="e.g. 'Short Distance', 'Long Distance'", max_length=100)),
                ('min_km', models.FloatField(default=0.0)),
                ('max_km', models.FloatField(default=0.0, help_text='Use a very large number like 9999 for the last tier')),
                ('rate_per_km', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_km'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Short name for code (e.g. 'standard', 'pragya', 'comfort')", unique=True)),
                ('display_name', models.CharField(help_text="Human readable name (e.g. 'Go', 'Pragya')", max_length=100)),
                ('base_fare', models.FloatField(default=0.0)),
                ('multiplier', models.FloatField(default=1.0, help_text='Fare multiplier for this category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
    ]
