# Generated by Django 5.2.13 on 2026-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_distancetier_vehiclecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an icon for this vehicle type (PNG recommended)', null=True, upload_to='vehicle_categories/'),
        ),
    ]
