# Generated by Django 6.0.2 on 2026-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0004_safe_city_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='enable_traffic_surge',
            field=models.BooleanField(default=True, help_text='Automatically increase prices during severe traffic delays'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='enable_weather_surge',
            field=models.BooleanField(default=True, help_text='Automatically increase prices during adverse weather'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='max_traffic_surge',
            field=models.FloatField(default=1.5, help_text='Maximum multiplier for heavy traffic (e.g. 1.5x)'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='max_weather_surge',
            field=models.FloatField(default=1.5, help_text='Maximum multiplier for severe weather (e.g. 1.5x)'),
        ),
    ]
