# Generated by Django 6.0.6 on 2026-06-25 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0005_pricingrule_enable_traffic_surge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Documents', 'Food', 'Electronics'", max_length=100)),
                ('markup_percentage', models.FloatField(default=0.0, help_text='Percentage markup (e.g. 10.0 for 10% extra)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Categories',
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Motorbike', 'Truck', 'Van'", max_length=100)),
                ('base_fare', models.FloatField(default=0.0, help_text='Base fare for this vehicle type')),
                ('per_km_rate', models.FloatField(default=0.0, help_text='Rate per km for this vehicle type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryWeightTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Light (< 5kg)'", max_length=100)),
                ('min_weight', models.FloatField(default=0.0)),
                ('max_weight', models.FloatField(default=0.0, help_text='Use a high number like 9999 for the highest tier')),
                ('markup_percentage', models.FloatField(default=0.0, help_text='Percentage markup (e.g. 20.0 for 20% extra)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_weight'],
            },
        ),
    ]
