# Generated by Django 5.0.14 on 2026-07-18 11:51

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0006_deliverycategory_deliveryvehicletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_delivery_geofenced',
            field=models.BooleanField(default=False, help_text='If True, deliveries are restricted to allowed service areas.'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_passenger_allowed',
            field=models.BooleanField(default=True, help_text='If False, this vehicle cannot take passengers by default.'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='allowed_service_areas',
            field=models.ManyToManyField(blank=True, related_name='allowed_vehicle_categories', to='core_settings.servicearea'),
        ),
    ]
