# Generated by Django 5.0.14 on 2026-08-05 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0007_servicearea_vehiclecategory_is_delivery_geofenced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('app_type', models.CharField(choices=[('passenger', 'Passenger App'), ('driver', 'Driver App')], max_length=20)),
                ('minimum_version', models.CharField(help_text="e.g. '1.0.0'", max_length=50)),
                ('latest_version', models.CharField(help_text="e.g. '1.1.0'", max_length=50)),
                ('force_update', models.BooleanField(default=False, help_text='If True, users on older versions will be forced to update.')),
                ('store_url', models.URLField(blank=True, help_text='Link to Play Store or App Store', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App Versions',
                'unique_together': {('platform', 'app_type')},
            },
        ),
    ]
