# Generated by Django 6.0.2 on 2026-05-15 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('DRIVER', 'Drivers Only'), ('PASSENGER', 'Passengers Only')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
