# Generated by Django 6.0.6 on 2026-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_city',
            field=models.CharField(blank=True, help_text='Filter users by city. Leave blank to target all cities.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_condition',
            field=models.CharField(choices=[('ALL_ACTIVE', 'All Users'), ('ACTIVE', 'Active Recently (Logged in < 7 days)'), ('INACTIVE_7_DAYS', 'Inactive (7+ days)'), ('INACTIVE_30_DAYS', 'Inactive (30+ days)'), ('HIGH_RATING', 'Highly Rated (>= 4.5)'), ('LOYAL', 'Loyal / Frequent Rider (>= 50 rides)'), ('NEW_USER', 'New User (Joined < 7 days)')], default='ALL_ACTIVE', max_length=50),
        ),
    ]
