# Generated by Django 6.0.6 on 2026-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_campaign_target_city_campaign_target_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='data_payload',
            field=models.JSONField(blank=True, default=dict, help_text="Optional JSON payload to pass with the notification (e.g. {'deep_link': '/wallet'})", null=True),
        ),
    ]
