# Generated by Django 6.0.6 on 2026-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_campaign_data_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='app_type',
            field=models.CharField(choices=[('PASSENGER', 'Passenger App'), ('DRIVER', 'Driver App')], default='PASSENGER', max_length=20),
        ),
    ]
