# Generated by Django 6.0.6 on 2026-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_fcmdevice_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
