# Generated by Django 6.0.2 on 2026-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduled_at',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_audience',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
