# Generated by Django 6.0.6 on 2026-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_rename_scheduled_at_campaign_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='message_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('driver', 'Drivers Only'), ('passenger', 'Passengers Only')], default='all', max_length=100),
        ),
    ]
