# Generated by Django 6.0.4 on 2026-04-21 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('headline', models.CharField(max_length=80)),
                ('body_text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('week_start_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdSlotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ads_per_week', models.IntegerField(default=4)),
                ('price_per_week_ghs', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Ad Slot Capacity',
            },
        ),
        migrations.CreateModel(
            name='AdExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extended_week_start', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='advertising.adbooking')),
            ],
        ),
    ]
