# Generated by Django 6.0.2 on 2026-04-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbooking',
            name='body_text_b',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adbooking',
            name='headline_b',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='adbooking',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='adbooking',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('DRIVER', 'Drivers Only'), ('PASSENGER', 'Passengers Only')], default='ALL', max_length=20),
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions_a', models.PositiveIntegerField(default=0)),
                ('clicks_a', models.PositiveIntegerField(default=0)),
                ('impressions_b', models.PositiveIntegerField(default=0)),
                ('clicks_b', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ad_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='advertising.adbooking')),
            ],
        ),
    ]
