# Generated by Django 5.0.14 on 2026-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_adbooking_body_text_b_adbooking_headline_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbooking',
            name='paystack_checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adextension',
            name='paystack_checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
