# Generated by Django 6.0.2 on 2026-04-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_chatmessage_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='dropoff_location',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='service_type',
            new_name='type',
        ),
    ]
