# Generated by Django 6.0.2 on 2026-04-15 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rename_dropoff_location_ride_dropoff_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='item_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='preferred_vehicle_type',
            field=models.CharField(default='standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('type', models.CharField(default='home', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
