# Generated by Django 6.0.2 on 2026-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_distance_remaining_ride_duration_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='base_fare_ledger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancellation_fee_ledger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_fare_ledger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_payout_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='surge_multiplier_applied',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_calculated_fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='waiting_fare_ledger',
            field=models.FloatField(default=0.0),
        ),
    ]
