# Generated by Django 6.0.2 on 2026-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_base_fare_ledger_ride_cancellation_fee_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='last_lat_update',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='last_lng_update',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='last_tracking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
