# Generated by Django 6.0.2 on 2026-04-15 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_last_lat_update_ride_last_lng_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('base_fare', models.FloatField()),
                ('distance_fare', models.FloatField()),
                ('waiting_fee', models.FloatField()),
                ('cancellation_fee', models.FloatField()),
                ('total_fare', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='rides.ride')),
            ],
        ),
    ]
