# Generated by Django 6.0.2 on 2026-04-16 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('max_discount', models.FloatField(default=0.0)),
                ('min_ride_amount', models.FloatField(default=0.0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('usage_limit', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='current_riders',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ride',
            name='gender_preference',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_riders',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='preferred_music',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='preferred_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rides.promocode'),
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stop_order', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.ride')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
