# Generated by Django 6.0.2 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_promocode_ride_current_riders_ride_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dispatch_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
