# Generated by Django 5.2.13 on 2026-05-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_promocode_user_alter_ride_preferred_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
