# Generated by Django 6.0.2 on 2026-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_dropoff_point_ride_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='stops_fee_ledger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ridereceipt',
            name='stops_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
