# Generated by Django 6.0.2 on 2026-05-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_deliveryproof'),
        ('rides', '0014_ride_stops_fee_ledger_ridereceipt_stops_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courier.delivery'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rides.ride'),
        ),
    ]
