# Generated by Django 6.0.6 on 2026-06-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_chatmessage_delivery_alter_chatmessage_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20),
        ),
    ]
