# Generated by Django 6.0.6 on 2026-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_alter_ride_is_scheduled_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
