# Generated by Django 5.0.14 on 2026-07-18 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_ride_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
