# Generated by Django 5.0.14 on 2026-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_alter_ride_dropoff_point_alter_ride_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
