# Generated by Django 6.0.2 on 2026-04-12 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LOCATION_SPOOFING', 'Location Spoofing'), ('UNUSUAL_FARE', 'Unusual Fare'), ('MULTIPLE_ACCOUNTS', 'Multiple Accounts'), ('FAST_MOVEMENT', 'Fast Movement')], max_length=50)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FLAGGED', 'Flagged'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='FLAGGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
