# Generated by Django 6.0.2 on 2026-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('comfort', 'Comfort'), ('luxury', 'Luxury'), ('delivery', 'Delivery'), ('pragya', 'Pragya (Tricycle)'), ('motorbike', 'Motorbike')], help_text='The vehicle category this plan applies to', max_length=50),
        ),
    ]
