# Generated by Django 6.0.2 on 2026-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya')], help_text='The vehicle category this plan applies to', max_length=50),
        ),
    ]
