# Generated by Django 6.0.2 on 2026-05-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversubscription',
            name='is_trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driversubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
