# Generated by Django 5.0.14 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_driversubscription_is_trial_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya'), ('motorbike', 'Flexy Motorbike')], help_text='The vehicle category this plan applies to', max_length=50),
        ),
    ]
