# Generated by Django 5.0.14 on 2026-07-16 06:59

import core_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionplan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=core_settings.models.get_vehicle_categories, help_text='The vehicle category this plan applies to', max_length=50),
        ),
    ]
