# Generated by Django 6.0.2 on 2026-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_color_vehicle_insurance_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadworthy_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
