# Generated by Django 6.0.2 on 2026-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_insurance_expiry_vehicle_roadworthy_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='go', max_length=50),
        ),
    ]
