# Generated by Django 6.0.6 on 2026-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya')], default='go', max_length=50),
        ),
    ]
