# Generated by Django 5.0.14 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('go', 'Flexy Go'), ('comfort', 'Flexy Comfort'), ('xl', 'Flexy XL'), ('exec', 'Flexy Executive'), ('pragya', 'Flexy Pragya'), ('motorbike', 'Flexy Motorbike')], default='go', max_length=50),
        ),
    ]
