# Generated by Django 5.0.14 on 2026-07-16 06:59

import core_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=core_settings.models.get_vehicle_categories, default='go', max_length=50),
        ),
    ]
