# Generated by Django 6.0.4 on 2026-04-12 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('AT_PICKUP', 'At Pickup'), ('PACKAGE_COLLECTED', 'Package Collected'), ('EN_ROUTE_TO_DROPOFF', 'En Route to Dropoff'), ('ARRIVED_AT_DROPOFF', 'Arrived at Dropoff'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('item_category', models.CharField(choices=[('DOCUMENTS', 'Documents'), ('FOOD', 'Food'), ('PACKAGE', 'Package')], max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_address', models.TextField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=50)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('proof_photo_url', models.URLField(blank=True, null=True)),
                ('estimated_fare', models.FloatField(default=0.0)),
                ('base_fare', models.FloatField(default=0.0)),
                ('distance_fee', models.FloatField(default=0.0)),
                ('final_fare', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('estimated_eta', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_deliveries', to='profiles.profile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
