# Generated by Django 6.0.2 on 2026-05-14 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('PICKUP', 'Pickup Proof'), ('DROPOFF', 'Dropoff Proof')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='courier.delivery')),
            ],
        ),
    ]
