# Generated by Django 6.0.6 on 2026-06-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0006_deliverycategory_deliveryvehicletype_and_more'),
        ('courier', '0002_deliveryproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='promo_code_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='surge_multiplier_applied',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_settings.deliveryvehicletype'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_settings.deliveryweighttier'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='item_category',
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_settings.deliverycategory'),
        ),
    ]
