name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: flexy_actions
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Starting CI/CD Staging Deployment"
            cd /opt/flexyride_backend_staging
            
            # Use sudo if the repo files are owned by root or www-data
            git fetch origin
            git reset --hard origin/staging
            git pull origin staging
            
            # Activate virtual environment and install deps
            source venv/bin/activate
            $PWD/venv/bin/pip install -r requirements.txt
            
            # Run migrations and collect static files
            $PWD/venv/bin/python manage.py migrate --noinput
            $PWD/venv/bin/python manage.py collectstatic --noinput
            
            # Restart Supervisor services
            sudo supervisorctl restart flexyride_backend_staging_replicas:*
            sudo supervisorctl restart flexyride_backend_staging_celery_high
            sudo supervisorctl restart flexyride_backend_staging_celery_default
            sudo supervisorctl restart flexyride_backend_staging_celery_beat
            
            echo "Staging deployment completed successfully!"
